-- PSQL MYSITE
-- USE TO BILIBILI.PY

DROP INDEX SPIDER_BILIBILI_FANS_COUNT_INDEX;
DROP TABLE SPIDER_BILIBILI_FANS_COUNT;

-- 这个正式使用表通过测试可以使用
CREATE TABLE IF NOT EXISTS SPIDER_BILIBILI_FANS_COUNT (
    ID int                  NOT NULL,           -- 粉丝ID
    NAME VARCHAR(600)       NOT NULL,           -- 博主名字
    SEX VARCHAR(8)          NOT NULL,           -- 博主性别
    FANS int                NOT NULL,           -- 粉丝数量
    CREATEDATE TIMESTAMP    NOT NULL DEFAULT NOW()::TIMESTAMP(0)WITHOUT TIME ZONE,    --新增时间
    PRIMARY KEY (ID)
);
CREATE INDEX SPIDER_BILIBILI_FANS_COUNT_INDEX ON SPIDER_BILIBILI_FANS_COUNT (FANS);




